import Clg from "./Clg"
export default function Nested(){
    const clg=[
        {
            name:" SIT Mumbai ",
            city:"kolhapur",
            tal:"Bhudarad",
            stude:[
                {
                    name:"Pranav",
                    id:1,
                    clg:"SIT"
                },
                {
                    name:"Omkar",
                    id:2,
                    clg:"SIT"
                },
                {
                    name:"Manoj",
                    id:3,
                    clg:"SIT"
                },
                {
                    name:"Prathmesh",
                    id:4,
                    clg:"SIT"
                },
                {
                    name:"Raj",
                    id:5,
                    clg:"SIT"
                },{
                    name:"Rohan",
                    id:6,
                    clg:"SIT"
                },
                {
                    name:"Pratik",
                    id:7,
                    clg:"SIT"
                },
            ]
            
        },
        {
            name:" K.H Collage Gargoti",
            city:"kolhapur",
            tal:"Kagal",
            stude:[
                {
                    name:"Pranav",
                    id:1,
                    clg:"Kh"
                },
                {
                    name:"Omkar",
                    id:2,
                    clg:"KH"
                },
                {
                    name:"Manoj",
                    id:3,
                    clg:"VIT"
                },
                {
                    name:"Prathmesh",
                    id:4,
                    clg:"KH"
                },
                {
                    name:"Raj",
                    id:5,
                    clg:"Kh"
                },{
                    name:"Rohan",
                    id:6,
                    clg:"KH"
                },
                {
                    name:"Pratik",
                    id:7,
                    clg:"KH"
                },
            ]
        },
        {
            name:" VIT Kolhapur",
            city:"kolhapur",
            tal:"Radhanagri",
            stude:[
                {
                    name:"Pranav",
                    id:1,
                    clg:"VIT"
                },
                {
                    name:"Omkar",
                    id:2,
                    clg:"VIT"
                },
                {
                    name:"Manoj",
                    id:3,
                    clg:"VIT"
                },
                {
                    name:"Prathmesh",
                    id:4,
                    clg:"VIT"
                },
                {
                    name:"Raj",
                    id:5,
                    clg:"VIT"
                },{
                    name:"Rohan",
                    id:6,
                    clg:"IIT"
                },
                {
                    name:"Pratik",
                    id:7,
                    clg:"VIT"
                },
            ]
        },
        {
            name:" VIT Kolhapur",
            city:"kolhapur",
            tal:"ajara",
            stude:[
                {
                    name:"Pranav",
                    id:1,
                    clg:"IIT"
                },
                {
                    name:"Omkar",
                    id:2,
                    clg:"IIT"
                },
                {
                    name:"Manoj",
                    id:3,
                    clg:"IIT"
                },
                {
                    name:"Prathmesh",
                    id:4,
                    clg:"IIT"
                },
                {
                    name:"Raj",
                    id:5,
                    clg:"IIT"
                },
                {
                    name:"Rohan",
                    id:6,
                    clg:"IIT"
                },
                {
                    name:"Pratik",
                    id:7,
                    clg:"IIT"
                },
            ]
        }
    ]
    return(
    <>
        <h2>Nested Looping</h2>
        {clg.map((collage,index)=>(<div key={index}>
            <Clg clg={collage} />
        </div>))
}

    </>
    )
}